### ISSUE TITLE
UPDATE with a multiple tables WHERE?

### ISSUE THREAD

**Issue by akurilin** [prowdsponsor/esqueleto#86]
I'm trying to convert the following raw SQL to esqueleto, but I've been unable to find examples of update with a where clause joining multiple tables:

```
UPDATE a
SET foo = 'bar'
WHERE b.some_col = true AND a.b_id = b.id
```

in equeleto it'd look like

```
update $ \(a, b) -> do
  set a [foo =. val 'bar']
  where_ ((b ^. SomeCol ==. val True) &&. (b ^. Id ==. a ^. BId))
```

But that won't work. Is that scenario above currently supported by esqueleto?

**Comment by sir-murray** [comment]
Should this issue really be closed?

I understand esqueleto does not support `UPDATE | DELETE ... JOIN` queries because they are just an extension available in, for example, MySQL. The only way to do the equivalent is using `WHERE` on tables that have not been joined.

Is there a particular reason this is not available? Or has it simply not happened yet.
Would it be possible to make other tables available to `WHERE` conditions through a pseudo join construct in the EDSL. Could the values to be updated/deleted be specified in the return statement to be consistent with `SELECT`?

For example:
```haskell
delete $ from $ \(a `With` b) -> do
    where_ $ b ^. BobAge ==. val age &&. a ^. AdolfId ==. b ^. BobBrother
    return a
```

I have only skimmed over the esqueleto code so I don't fully understand what is hypothetically possible.
I don't want to dive in and then realise days later it's not possible.

**Comment by meteficha** [comment]
@sir-murray We have to strike a balance with respect to completeness, correctness and development effort.  Adding `With` is probably doable, but:

  * It's a seldom needed feature that has a workaround.

  * It will introduce issues if one used `With` on a `select`.  Or would need to complicate the types even more to disallow such usage.
