### ISSUE TITLE
string aggregation

### ISSUE THREAD

**Issue by bburdette** [prowdsponsor/esqueleto#98]
Postgres has a string aggregation function, example below.  Seems like it would be nice to have.

```
my_database=# select * from dues_rate;
 id |    name    | amount | club 
----+------------+--------+------
  1 | student    |  25.00 |    1
  2 | recurring  |  65.00 |    1
  3 | regular    |  75.00 |    1
  4 | family     | 100.00 |    1
(4 rows)

my_database=# select sum(amount), string_agg(name, ', ') from dues_rate;
  sum   |              string_agg              
--------+--------------------------------------
 265.00 | student, recurring, regular, family
(1 row)
```

**Comment by Philonous** [comment]
It's not very well documented, but you can use [`unsafeSqlFunction`](http://hackage.haskell.org/package/esqueleto-2.2.7/docs/Database-Esqueleto-Internal-Sql.html#v:unsafeSqlFunction) (import `Database.Esqueleto.Internal.Sql`) to write your own binding. 

Here's an example (completely untested):

``` haskell
stringAgg :: SqlExpr (Value Text)
          -> SqlExpr (Value Text)
          -> SqlExpr (Value Text)
stringAgg expr delim = unsafeSqlFunction "string_agg" (expr, delim)
```

Please note that you _have_ to write a type by hand, since unsafeSqlFunction does not know about postgres' types (hence the "unsafe" in its name). 

Just for good measure here's a function I do actually use in production:

```haskell
arrayAgg :: SqlExpr (Value a) -> SqlExpr (Value [a])
arrayAgg = unsafeSqlFunction "array_agg"
```

It would be neat if someone where to create package for postgresql-specific functions :wink:

**Comment by meteficha** [comment]
Thanks for the suggestions, @Philonous!  `esqueleto-2.2.8` contain both `stringAgg` and `arrayAgg`.
